---
abstract: 'validate characters for XML'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
keywords:
  - xml
  - characters
  - utf8
  - utf-8
  - valid
  - invalid
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Char
provides:
  XML::Char:
    file: lib/XML/Char.pm
    version: 0.01
resources:
  bugtracker: http://github.com/jozef/XML-Char/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/XML-Char.git
version: 0.01
